import React, {StyleSheet} from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f3f3f3',
    },
    baise:{
        color:'#fff',
        fontSize:18,
    },
    headrigbox:{
        flexDirection:'row',
    },
    headrigimg:{
        width:20,
        height:20,
        marginLeft:15,
    },
    caixiagtop:{
        width:global.__WIDTH__,
        height:35,
        borderWidth:1,
        borderColor:'#eee',
        backgroundColor:'#fff',
        alignItems:'center',
        justifyContent:'center',
        marginTop:14,
    },
    caixiagtoplan:{
        color:'#2d8ef3',
        position:'absolute',
        right:15
    },
    caixiagmid:{
        height:50,
        backgroundColor:'#e3f6ff',
        paddingLeft:15,
    },
    caixiagmid1:{
        flexDirection:'row',
        height:25,
        alignItems:'center'
    },
    cailist:{
        marginTop:14,
        borderWidth:1,
        borderColor:'#eee',
    },
    cailist1:{
        height:35,
        backgroundColor:'#fff',
        borderBottomWidth:1,
        borderColor:'#eee',
        flexDirection:'row',
        justifyContent:'space-between'
    },
    cailist2:{
        height:35,
        justifyContent:'center',
        borderBottomWidth:1,
        borderColor:'#eee',
        backgroundColor:'#e3f6ff',
        paddingLeft:15
    },
    cailistcon1:{
        flexDirection:'row',
        justifyContent:'center',
        marginRight:15,
    },
    cailisttu:{
        width:15,
        height:15,
        marginTop:10,
        marginLeft:15,
        marginRight:10,
    },
    shitime:{
        flexDirection:'row',
        marginLeft:15,
    },
    shitimez:{
        marginRight:10,
    },
    cailiszi:{
        marginTop:8,
    },
    lansezi:{
        color:'#2d8ef3'
    },
    cglistbox:{
        width:global.__WIDTH__,
        paddingLeft:15,
        paddingRight:15,
        borderBottomWidth:1,
        borderColor:'#eee',
        backgroundColor:'#fff'
    },
    bianhaobox:{
        justifyContent:'center',
        borderBottomWidth:1,
        borderColor:'#eee',
        height:35,
    },
    cgoucon:{
        flexDirection:'row',
        paddingRight:15,
    },
    caiglisttu:{
        width:40,
        height:34,
        margin:18,
        marginLeft:0
    },
    cgouconr:{
        borderBottomWidth:1,
        borderColor:'#eee',
        marginTop:16,
        width:'96%',
    },
    cgouconrg:{
        flexDirection:'row',
        marginTop:1,
    },
    cuhei:{
        color:'#333'
    },
    dahong:{
        color:'#ff5959'
    },
    mar10:{
        marginLeft:10,
    },
    sancon:{
        color:'#333',
    },
    sansan:{
        marginLeft:10,
    }


})

export {styles as default};